apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2akNDQWRLZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1EY3dNekF4TWpBd01sb1hEVE16TURZek1EQXhNalV3TWxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS1BjCmc1NURublNaK3RndkRDQ0IxNUtZTXV3cURVRSsyTU9mT3NtcTEzdE8rbUlIR1FHbi9KakVZRnFhQ1l6ZnpQM1UKMFFYMGg4ZkxnSUEwaURjYmdvandzV0lOR0E0dUZoK2R3bWpWWFlLL3IxbGI0UEQ4cnBvZGNZQXpvZVV2SkhLdwpGeHZwa0FsdXVIK0xvQTdObXpuRVRsRHM5bzBjVXRpellnZzcvN3lOeXRVdmkrY3pmWSswMkhleENwVmpsaEJQCmQxTXNONDdITURDYmFVWVZmbE12RnNhY0FPZTFtZmZSV3dXd3NZcFN3WS94WFdVaWl3YVJBVTNtQ0p6Um9TN04KOGQ5RlIxV2l6RmlzQ2c4cjJ2NTEyWUp3RDEwNk1OeDVlSlpqRmpkNEdRWVZEbjJuN00zUCtFUTRLMmhoaXJregp2dld5K1Z3VWVtM3A3WXRUa0s4Q0F3RUFBYU5GTUVNd0RnWURWUjBQQVFIL0JBUURBZ0trTUJJR0ExVWRFd0VCCi93UUlNQVlCQWY4Q0FRQXdIUVlEVlIwT0JCWUVGRGN6ZkExUjMxc2NOWm9IV0tHUld6Sk51YzJQTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQjFKSXpLY0RoWlg4TG05ckdOdTl2TlUzTk83S1phYjUxRGlIK2YxaUc4UDVMVApFN05oa1VRWFdjdXhZbWxWTTk5K3hIUlFuSGRxcDZUSUhlaGZiSXI3S1BwQXNIMjVjd3puK0hUMWUvaDlsaWZLCml2K0dOVGF4UmFvSmVFb01DRzBMbVVsalNaSXAzN1czelNMM3BXRTgzbnc1VmZDRDF3d0lzeTdXN1p6Vk9EamMKbXI1d1gwbkJpWWVZSmNTUDBWV21jMGNCMU1YYWZFYW5JdnJaWkRTT3BEeW9iVU9UNysrRkNuOHlvOGVNOUdKQQpCdDloUU15cFRYWUMwb0IvSDdLKzJtR2xVam0rZlNZY2ppVWdGR09PdHNWdXVIdDN0WSt0WmxUaEN5ZndmSlhSCmsxOGlaa1BhWkl0V2VSb0lheVlkKzhRaFdwaHRFVjA4dndmQkRMNnAKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://61.109.215.14:6443
  name: smtbrc-prod-api
contexts:
- context:
    cluster: smtbrc-prod-api
    user: smtbrc-prod-api-admin
  name: smtbrc-prod-api-admin@smtbrc-prod-api
current-context: smtbrc-prod-api-admin@smtbrc-prod-api
kind: Config
preferences: {}
users:
- name: smtbrc-prod-api-admin
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: kic-iam-auth
      env:
      - name: "OS_AUTH_URL"
        value: "https://iam.kakaoicloud-kr-gov.com/identity/v3"
      - name: "OS_AUTH_TYPE"
        value: "v3applicationcredential"
      - name: "OS_APPLICATION_CREDENTIAL_ID"
        value: "b4ef7202e169497f8d15c3718c1a87ab"
      - name: "OS_APPLICATION_CREDENTIAL_SECRET"
        value: "WTkhB0xC00yKWQs6jnYl2inO9LJ-ZKwrKB1AEhQrxPbSETF6B9dY7Kf189OgtK14rGN7Erysc70znlQ-rWuw9w"
      - name: "OS_REGION_NAME"
        value: "kr-gov-central-1"
