apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2akNDQWRLZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1EY3dOREF6TXpFek9Gb1hEVE16TURjd01UQXpNell6T0Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTzg1Cms1RjhrTndoTE4yUFVrQ3U2S3dQcGswSG9EUjZOMTc3bytnUEV2VVJXeUhaenJTZGR4bStVR2dzWnNINVBNMHcKVjk2eXZhVzFZOXZYZmNrRXRNeHN6WTltY2NoN2JsZWZNYWQrNUM2aklYeDlJdWhJSTBiVFZ3QWlNRmxxNDR4Nwp1Z2h2Rk1DUXYxSXd2UmRONjdQU0ZIQzd6Sll2T0kxWlQvYk5TYlRGWHFlb0hzN2lhaXRCaEs1TlBjczMwYWcvCnBkK20vdDVyNGhFdmw0YXVRejFQYmNZNjV2MDZtQzZxRmF4cVZOWXNqZkl4UlJGRkJKQU0vSGpDUDA1TXpyTXAKNi9mbTIrZTZ4eHVqZEszaDdTUElvdFZnMXVLY1JYUkJtazJ6SWZBRTNtSENCOVErZ1BtbzJzeWpHL1hKcEtrNQpNcTBjVmx4elE1N0d3WmgrUDc4Q0F3RUFBYU5GTUVNd0RnWURWUjBQQVFIL0JBUURBZ0trTUJJR0ExVWRFd0VCCi93UUlNQVlCQWY4Q0FRQXdIUVlEVlIwT0JCWUVGSW9LNXJDWlg5S2FIZ1A3U3lsQy8xenREVzNRTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRRG53N3hjN0pLRmoyc3VUL0Q4cHhTaWZzSDJOLzRGbE1qakc4eU1JSWR0dkJTMAowUERjR3ROdExOVUk5UEFDbU04VkYyUGw2NHdDQXZLMXlKcWorZFViZmRRR1lXWGFob1dSZkVqTzBIS2ZyM0NTCldrVE0xSVY1NzJVR1JuSlpxaU94Ny9BdWJTbDBJdUs3YmFuMlVobTFEODRScVB1OXFjTzczaEpqM3diSXNEdkgKNjhHdk94dWpMY3ZXck5TN2cyeW5ucXAxNng0aW1MT0JmMU1NNFZNS09KbXNvdkRFL3VzUE01NUtxS3hvaElESApUVnd3cE9uZW9aYXE4UHB1QlZBdnNHMDN1MHVHeEV3VzljVlcvYXVnUlVEUm5EY29aeXdOakpSeWpVRlJlRjhUCkRxQzQxVTg2NHUxYUtKL3Q2Ym1hSkw4eUF0MEU4ZjFGaFYwOThvTGwKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://61.109.215.123:6443
  name: vmssvc-prod
contexts:
- context:
    cluster: vmssvc-prod
    user: vmssvc-prod-admin
  name: vmssvc-prod-admin@vmssvc-prod
current-context: vmssvc-prod-admin@vmssvc-prod
kind: Config
preferences: {}
users:
- name: vmssvc-prod-admin
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: kic-iam-auth
      env:
      - name: "OS_AUTH_URL"
        value: "https://iam.kakaoicloud-kr-gov.com/identity/v3"
      - name: "OS_AUTH_TYPE"
        value: "v3applicationcredential"
      - name: "OS_APPLICATION_CREDENTIAL_ID"
        value: "b4ef7202e169497f8d15c3718c1a87ab"
      - name: "OS_APPLICATION_CREDENTIAL_SECRET"
        value: "WTkhB0xC00yKWQs6jnYl2inO9LJ-ZKwrKB1AEhQrxPbSETF6B9dY7Kf189OgtK14rGN7Erysc70znlQ-rWuw9w"
      - name: "OS_REGION_NAME"
        value: "kr-gov-central-1"

