apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2akNDQWRLZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1EWXlNREF4TlRVME9Wb1hEVE16TURZeE56QXlNREEwT1Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTlhmCnBpajVCdmFnZjFVSzhFVGZvTG1RL2ZmNUg2ZGJBcnlnTHhJOGhQUEQ5aXIrK0QwRCt2MTlnUXRjdzFpc1BGWmoKdVBoV3dwUlZxckNLdU90T2Y3UWFxVm1DeFZlenEwNDhQVG56MSt3NjdWS2pwRG5sMnZKeUdsSTBoNlFUaUxkRQprVjlFNnlnN1duVlRXOHBQRlN6Q1E2VkdRem5ESWw0clB1MlFpS21OcDJuY1pyOGphanV6blVXWkhoQjVhdHA2CjFva1U2d3J5SXZMS3ZuVkZ1bm1IQllJMFpQV2o5Wm5iQkJ4TEdNTFRVZzV0VEJHeVgxZ0RyS0FFNVZ6MmQrNDIKNjd5WDJzZm1CckliRzJjYjFXTXdXTU90MGlDVWtMbWpGTXNvT2ZIdVpqN0NGcGpYQ1JuOVFWWnlFY2ZxYWdvOQpZRHR6TkhpdEkrRno4Ty9Bb01jQ0F3RUFBYU5GTUVNd0RnWURWUjBQQVFIL0JBUURBZ0trTUJJR0ExVWRFd0VCCi93UUlNQVlCQWY4Q0FRQXdIUVlEVlIwT0JCWUVGSld2aE1mNjFEbXZLd0ZVZzZyaHRFMzg0TzZlTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQkFKSWRiQjdtUEpnVXhLREFlZ2xTckYvelZGS1hqQUZVVFdnUE1wcGRUS2NuUwpUczgvVUEvY2FueW9qQTAvRFNnNThhZmRHS1B4cUtLU0RSdm1rMmpSdkpJVkd6TjFIaVYvbzAwSzVoOG16cEFQCjFCelp4UnNienZQLzdVL2VnbkgrQXBScVZ2K3ZBbXNMbDkxRWNqcDI2VGhQS1dpaXVZVzYyKzg4MTA3YjFXdUoKSkZRMFV5UGZlMjFaaGNuZTZBVlJvelJxcTUxYkR2KzJRR0R4QmFJMjJkL0s5SFh4cVFoVWpsNnFmTkQ2ODBaSQpXMXFsYWxTdWw0ZkJablk2L2dGZzl5NHZCbWdYYmRYTFlOZytyOGZIUlcyMEZsWWNBWDFVR0xzMnBTZzFkYVdECjV6VkhZOElZdlQwZHdmOGU5VlFSaGp6N1pVcW1FaFFyZCtxaXVoU0EKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://61.109.215.91:6443
  name: smtbrc-prod-monitor
contexts:
- context:
    cluster: smtbrc-prod-monitor
    user: smtbrc-prod-monitor-admin
  name: smtbrc-prod-monitor-admin@smtbrc-prod-monitor
current-context: smtbrc-prod-monitor-admin@smtbrc-prod-monitor
kind: Config
preferences: {}
users:
- name: smtbrc-prod-monitor-admin
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: kic-iam-auth
      env:
      - name: "OS_AUTH_URL"
        value: "https://iam.kakaoicloud-kr-gov.com/identity/v3"
      - name: "OS_AUTH_TYPE"
        value: "v3applicationcredential"
      - name: "OS_APPLICATION_CREDENTIAL_ID"
        value: "b4ef7202e169497f8d15c3718c1a87ab"
      - name: "OS_APPLICATION_CREDENTIAL_SECRET"
        value: "WTkhB0xC00yKWQs6jnYl2inO9LJ-ZKwrKB1AEhQrxPbSETF6B9dY7Kf189OgtK14rGN7Erysc70znlQ-rWuw9w"
      - name: "OS_REGION_NAME"
        value: "kr-gov-central-1"
      provideClusterInfo: false