apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2akNDQWRLZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1EWXlNREF4TlRNMU5sb1hEVE16TURZeE56QXhOVGcxTmxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSnRMClMzZjZud0FlT3JBMlpDS1JIbVVadHlQMmZlN3U4VEpVTUt3bEFOYWxGdVhKMGpUcVlFYXM1K1lTaXBKSmQ3cjcKdDZVT3JtNUphRWlxelhOTGJ6aWJOcXJQNXExK0x1R0VHUTUxakIwdjMwdEk1QVdnWVZUSzB5UWNTdm5uL1h4VgpQcnhxdEZrWUdNeFRub25PbU0vamw5aEFSSnArVzYxTnZGYnoxWHIxVStiNXlRM3poa0ZaQ2t1b3dQYkVFK0JYClVodkVTcU9LUnlrVHdIYkRCRUtZRUZRZ0RKOGdhdTFCdURaTmdpdzcxNTBQRkR1MjZlL1JlQ0JBNE9hZUl1a1YKbDZQci9VN1R5RE1URGVqSlhaQmVIT3dqRGdVeHB6ZmorWmlJWTZweTE3V3RQMHpsWTc1dzVBd3p6K1dRNjJZYQpFWTYwSk5EdlpmMWRMTWtRZHVjQ0F3RUFBYU5GTUVNd0RnWURWUjBQQVFIL0JBUURBZ0trTUJJR0ExVWRFd0VCCi93UUlNQVlCQWY4Q0FRQXdIUVlEVlIwT0JCWUVGR0VQTzB6REY2REYxenozOUQ3V0JIVUE5WDNqTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQURBdzdQeXRjc3NNU1ZoTStaQ2pVR2xiNkVRbHpONnl6U1RMU0RHUzdwaEk0RAowK3ljK0JIeis3aEN4SUZUcGp3MmVqcU05K0h1cnpjelcveU1SQU9EUVhxZHhkOWJVRVdteHhpbTA2UU4yVTk2CkhaS1lFODJOaUsyVS84SmFVNnB3M1gvZkFtbk5LWUd0ejFLNWVPRUlKcDk4L240QXBxclE2VzVWcGV5RXJsaUoKT005b2tpRzZCU3dqczJ4YUxjUDB2K0ljajZsUnp4RmpjclBLSjQ3SFYxZXd5RnFXaU5yM2tMcDhkK3ZYUlpRVwozMzNVTEd2NXhLZEl5OWhYcXR3NHRyK3ZkYllVMFN1RjRKelhhRGN6VzE3SU1qcmlJWVc0aE5Ud29rUFJTZlVzCk5vUERkV2Z3VC93bEdZSDRJUUZMd1VieDJCaVJUWjU1WXpSZFZGSU0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://61.109.215.239:6443
  name: vmssvc-prod
contexts:
- context:
    cluster: vmssvc-prod
    user: vmssvc-prod-admin
  name: vmssvc-prod-admin@vmssvc-prod
current-context: vmssvc-prod-admin@vmssvc-prod
kind: Config
preferences: {}
users:
- name: vmssvc-prod-admin
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: kic-iam-auth
      env:
      - name: "OS_AUTH_URL"
        value: "https://iam.kakaoicloud-kr-gov.com/identity/v3"
      - name: "OS_AUTH_TYPE"
        value: "v3applicationcredential"
      - name: "OS_APPLICATION_CREDENTIAL_ID"
        value: "b4ef7202e169497f8d15c3718c1a87ab"
      - name: "OS_APPLICATION_CREDENTIAL_SECRET"
        value: "WTkhB0xC00yKWQs6jnYl2inO9LJ-ZKwrKB1AEhQrxPbSETF6B9dY7Kf189OgtK14rGN7Erysc70znlQ-rWuw9w"
      - name: "OS_REGION_NAME"
        value: "kr-gov-central-1"
      provideClusterInfo: false
