apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2akNDQWRLZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1EY3dOREF6TXpRek9Wb1hEVE16TURjd01UQXpNemt6T1Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTW1QCjh4VTA2REVVeUNSNEZYZmk1SzNnNVZzMnRVWWpGaHFxVTU2OUNTazhJQTd4ek1pRGlNcmhvOWFIL3d2VWRNSFoKTjJCeUhmbHB4SkVYcm1RSGF4bjk4RnFOSGM2TE1zT2FGNVowUkRwYWJOc3VsSmxXTzlBSXJHOVJ4UVREcjFUegpvbjNFZWcyU2Jhd2o2ZVFKTzdIbHMydlRCUTc0T1ZhTWtLcGR2endnL2VPb1o4YUVqb0JoaEVwaVFvZVZSNXJGCkUwdXFGQUJ5UlBFOWt5ZmllN3dzcVdIQUMyUEYzekxIcUJTWUE3cys4c1IycUhQSnBzU2ZxM2xUWDhYcVpqSFQKdmtubG5XYmFzT3F3c01vK1lMTm9XNDFUNksraktEZS9sQk5xc0kza2thTnprTEdvMTFQdDBGeVRxOGVlRHBJbwpZdG4ydWlQSzdXM1JqWFZqeUljQ0F3RUFBYU5GTUVNd0RnWURWUjBQQVFIL0JBUURBZ0trTUJJR0ExVWRFd0VCCi93UUlNQVlCQWY4Q0FRQXdIUVlEVlIwT0JCWUVGSldraW9tOFF2cXRPNEVYM1FEbGl6Y25PUGdZTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQVd2N2Zlc0czLzVxTHVyT0M3K09kQmtHYzRxSzUycFBadmVvRHVpbTZQaFFhZAphZSszVmNFWXVrTDA0clRCTjRHSEM3L2pXeUwwdTdzOXIrSXFKWXdldWh3cWc3U3huV1dONzVwTStkUENQdHQ0CmdJNmx5ZmFldzZJakYwUTUrWjRsTHBOZDNIYktVVVV6UEJ6bkkvd0FBNGhVdlZxOEJ5Qjk4UU8zNnB4aUt2LzgKUDU3RHpNcWo5UHZzNlJyamVkQjM4RkNkUjdlOEl6ejBQaDM1TWRnalVsa1k5Q2Vrd2QraVRxdlNVSTYzRG1CeApmV3RHdHNydzBibXJIdnRVZ0d4eG14YldHWFdhMkN0WE0vSk5yaENhdXFhRERZZklrTE9wa1NuSE41UmpFdENVCkpidGFzdHNBSjFKTkVBdVhiY1JpRzc2bTVxaGVaYk4veTFYRnlzcHkKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://61.109.215.200:6443
  name: smtbrc-prod-monitor
contexts:
- context:
    cluster: smtbrc-prod-monitor
    user: smtbrc-prod-monitor-admin
  name: smtbrc-prod-monitor-admin@smtbrc-prod-monitor
current-context: smtbrc-prod-monitor-admin@smtbrc-prod-monitor
kind: Config
preferences: {}
users:
- name: smtbrc-prod-monitor-admin
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: kic-iam-auth
      env:
      - name: "OS_AUTH_URL"
        value: "https://iam.kakaoicloud-kr-gov.com/identity/v3"
      - name: "OS_AUTH_TYPE"
        value: "v3applicationcredential"
      - name: "OS_APPLICATION_CREDENTIAL_ID"
        value: "b4ef7202e169497f8d15c3718c1a87ab"
      - name: "OS_APPLICATION_CREDENTIAL_SECRET"
        value: "WTkhB0xC00yKWQs6jnYl2inO9LJ-ZKwrKB1AEhQrxPbSETF6B9dY7Kf189OgtK14rGN7Erysc70znlQ-rWuw9w"
      - name: "OS_REGION_NAME"
        value: "kr-gov-central-1"