apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2akNDQWRLZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1EWXpNREEyTkRReU5sb1hEVE16TURZeU56QTJORGt5Tmxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTlRaCmRiNTNiZmg2QmpzeiswMEJZaWw2bzk4TmFvbktzZ29mdlQrUnRpQ3RLQ1loV0o5dU9yWjltZWVLRVFqT1lrSXoKOUV3VGRPOXQ3aXU4YWkzanFrY05rOU11VnRrQ2pudG1BV2dpalkvT1RPcUloZis5M0lRT05rOFNjNVVTc3VZNQpQQU9Lb3QyMkhSeFJqcWQwUW5PK29LOXpWeTRoWnpUeUFRazk2dDRraGliQWNmMVNXZEpabVdiZkhIdm9UYTZ2CkdaaUkxZzhyT0hSZ01rckpINXVtU2R6QVFNMjlRby9xWXJtUkt0bi9INUpCT3ZLMkJ1Vkh4VHJHeUdicENaazUKLytNaC8zZVFDcGoxTUg5K2dOeFNJWW55NmJFZXpFZnQ3Tk9LbDBGYTlaY2sraDdOTTNnTlRJZjBzMXB3Yi9EYwpMbmhwRGpXcUF1N3VtSGlWYW5zQ0F3RUFBYU5GTUVNd0RnWURWUjBQQVFIL0JBUURBZ0trTUJJR0ExVWRFd0VCCi93UUlNQVlCQWY4Q0FRQXdIUVlEVlIwT0JCWUVGRjRrcEJ3T1ZZY2JTZ2E5M0N2Q3FGbGl6TUtuTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQ2EyOGdDbEZ2OGlNNWk5VnJOaHI2cndOYjYwaDJwYTllU1lhOG9WMlcyS0dtSwo2bGdmZHcwY2pucHE3OUlsQ0s2clVKZHpDdG5iTWoreHF1Z0RpSW85OG00TWRPYjJNZ1RTUG5iSXA1aHdlZm91CmJYM3BtWURzOU5ZYVRxM1A2NTg4aVJwQ2xhRWlaWU9KQUlwS29TVHBWWjZia1R1NVNCaHFld2FnSnUzVkhvMDQKaGV6QXpRZzBEa21hdmU1RHRIUFNPTkFUcWdlaFdSSGErUjVENFp6dGx1RXVOM0hValRCVUpPRzBEbzMvai9TRQpxelZxaWYzUFZsUXJKNnV4dWZXaFA4b0FDSmNySm9hTEQrdmpXeDE5SEgyTUFmZHJ5endWSkRRMkg5SmRneFViCkdUSVl3dDF0c0drbDJVbDdKUFBxMGdQWHpJWSsvYTF6dTVmTndZY3gKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://61.109.215.233:6443
  name: smtbrc-prod-mgmt
contexts:
- context:
    cluster: smtbrc-prod-mgmt
    user: smtbrc-prod-mgmt-admin
  name: smtbrc-prod-mgmt-admin@smtbrc-prod-mgmt
current-context: smtbrc-prod-mgmt-admin@smtbrc-prod-mgmt
kind: Config
preferences: {}
users:
- name: smtbrc-prod-mgmt-admin
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: kic-iam-auth
      env:
      - name: "OS_AUTH_URL"
        value: "https://iam.kakaoicloud-kr-gov.com/identity/v3"
      - name: "OS_AUTH_TYPE"
        value: "v3applicationcredential"
      - name: "OS_APPLICATION_CREDENTIAL_ID"
        value: "b4ef7202e169497f8d15c3718c1a87ab"
      - name: "OS_APPLICATION_CREDENTIAL_SECRET"
        value: "WTkhB0xC00yKWQs6jnYl2inO9LJ-ZKwrKB1AEhQrxPbSETF6B9dY7Kf189OgtK14rGN7Erysc70znlQ-rWuw9w"
      - name: "OS_REGION_NAME"
        value: "kr-gov-central-1"
      provideClusterInfo: false