apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2akNDQWRLZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1EWXpNREF6TURNME5Gb1hEVE16TURZeU56QXpNRGcwTkZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBUEhoCmx5U1d0cDRMRmswMFV4NGJ4L1MrSloxWlI3NlEybU54Ujd6VTdocVpQZGpyWUpkWDZaYnJQTWgvRUM3UXpsTkgKbjVHbmJ2bU43YkZQQjlSSVkweU1ES3paUVVlUXlEYTA1MStpOWJBMSsrMVZRY2N1SzQ0Zm4raXlJWnpnU2R5aQovcXJNOVJlMDN1a0JSdkg4R0pNNHhoSHJXT0F0S2Noa3c0QnBFYVBRZUVsT3l2NjJ5bnhic1FxSVduZEU0S2pyCnBJR3dBTE83ei81NXA3QUNhbXZNUzUyZ3dZcmNsL3JZVU5pSDJGcSt1QW5kS2xncG9WcWp1WFhDUDdtWklGLysKTlJad291QUptcDFia1RQOU1pZ053WUpXdnpZcisrWkQrNTVmM1JOcnRUTGpFb2U2Z2Nha0VlcGV3cDN6dFh5VgpvYVNmL2RLNTlPSnZkRWptSk84Q0F3RUFBYU5GTUVNd0RnWURWUjBQQVFIL0JBUURBZ0trTUJJR0ExVWRFd0VCCi93UUlNQVlCQWY4Q0FRQXdIUVlEVlIwT0JCWUVGQWM4Vi9udE1zRFNJZWZCZ1hKN0xObmZqZDVNTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRRGYzTTFhR2dxQnA2TURtK2hFRUp4R290K2thOFY4VTVXcmt3MFhXeWo5Zm5JUgpuZEpsRFdRMlNqZWMrTFdXUlRLUlFXc0lGcW1nb3I2QS9xSnBpRzNhSFVzbDk0eXZYUi8vMHZzY3J6b0VOamsxCnlHVFYwWUZFcEVvUWtsUGRWU2ZGV2hMbmgxNXBrNzQ3ZHk0c3FIYTNLUEVlRWVOYnpnQllsdUJDYlM1NGZ3dkkKbkhLTWU4MzlySS9jbC9VRjE1SklvK2M0TVhOeXNRZnZxaXN0RG8xa0xSajdGZ2loakJpT2k2QjJZdjNrdlU2cwpLbzdleE5mSXJLWk1QL2IzeURWQUJ3eHhQcHpTWTlTdmZoTnFGWFdwSkpRSm1jS1ZNbjk2UWxpd05NZ0oyc2FqCnRkODZZNEhENDlEcFVON010RnNrUFJsT0hTODdSc2lWS05VNUs0U3oKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://61.109.215.172:6443
  name: smtbrc-prod-web
contexts:
- context:
    cluster: smtbrc-prod-web
    user: smtbrc-prod-web-admin
  name: smtbrc-prod-web-admin@smtbrc-prod-web
current-context: smtbrc-prod-web-admin@smtbrc-prod-web
kind: Config
preferences: {}
users:
- name: smtbrc-prod-web-admin
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: kic-iam-auth
      env:
      - name: "OS_AUTH_URL"
        value: "https://iam.kakaoicloud-kr-gov.com/identity/v3"
      - name: "OS_AUTH_TYPE"
        value: "v3applicationcredential"
      - name: "OS_APPLICATION_CREDENTIAL_ID"
        value: "b4ef7202e169497f8d15c3718c1a87ab"
      - name: "OS_APPLICATION_CREDENTIAL_SECRET"
        value: "WTkhB0xC00yKWQs6jnYl2inO9LJ-ZKwrKB1AEhQrxPbSETF6B9dY7Kf189OgtK14rGN7Erysc70znlQ-rWuw9w"
      - name: "OS_REGION_NAME"
        value: "kr-gov-central-1"
      provideClusterInfo: false
