apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2akNDQWRLZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1EY3dOREF3TXpJMU9Wb1hEVE16TURjd01UQXdNemMxT1Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS2VTCmlHUXh3RythektBL3FnT3ZMUGo3RkRMY2NrVjRPN244aitKZ3RpTElLbE5QTk1xL3A4NEw3L2l2QWdjL0kyemMKUXVlZmozcWtSSXIzb0NGTDVHVkkvaU5JazJZQVNIY1J3WW5uQytPdXJKTmdlN3A2UEhYaVd3RkJ3MldBUDcxMQpqb2FwbWhTdmIzV0NiRjBHTzVBRS80WjFzcnM4VXJFb09BaFEwVTNuTDR1RURPeUFpV0NZRlJHVm5HaXRvN2RpClUzWmJ6NlZTNHhIckJvOXlzcXl3Zi9waVF5TDJWcEpwbVZtQ3VKcnJOeUVOaXh0RXY4RlRIREVXbURadHI4aDMKeXdZeFFDYXA2dmJudWJFTHhaSHBiSklQaUZ1SUdDNWtudGpwbTVncmN6NnA3anBjTytHSjMwUDU2RG1TbU1rawpKSUR2QTYyN2wrZmllRHZ4TVEwQ0F3RUFBYU5GTUVNd0RnWURWUjBQQVFIL0JBUURBZ0trTUJJR0ExVWRFd0VCCi93UUlNQVlCQWY4Q0FRQXdIUVlEVlIwT0JCWUVGR3ZQYWQrUVJJM1FNMGQ5eFZtZjk0R2MxM1gxTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQkdGSUZwdWxJZlJURFFTU3VoRnlzSTNTN1p2OCtmL3pBV1h4NFR0QkpidjBrVgppMERzWWgySmlRSTB5WnFZc2wzaFAyTmdha3RDeGxpcDJpU2x0RVlXK1NFandrWUFrR09zTWJNVFlmK1k3azZXCkJRdVBaYmFZKzQyNDNaQ0Ywd2pGdlUzTjVDQUlHMENTelpkTStsbzYyNnJXN042UUpPa3l3NzBvNmFRV3IvR3cKVC9aVU52MGFqOGU3TEpYOW1TclFvcDA5NHdJOWtvSWFOVTRhenF0aC9HemNPa09XajhRa25yUkdySlBYQUpvNQo1bGRNR2dnVTFXWEFUcXFwT2w4b1Nxdkg4OHE0REV0cDlJdFM4cVgrMkJmMEhkN2p6NHhHaXN0Y2hoeHhzWkdwCk85YmVuamFoeXZtbDlDbmcveGpteDN5R0hBREtUYzBaeG9OU0VtYSsKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://61.109.215.105:6443
  name: smtbrc-prod-api
contexts:
- context:
    cluster: smtbrc-prod-api
    user: smtbrc-prod-api-admin
  name: smtbrc-prod-api-admin@smtbrc-prod-api
current-context: smtbrc-prod-api-admin@smtbrc-prod-api
kind: Config
preferences: {}
users:
- name: smtbrc-prod-api-admin
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: kic-iam-auth
      env:
      - name: "OS_AUTH_URL"
        value: "https://iam.kakaoicloud-kr-gov.com/identity/v3"
      - name: "OS_AUTH_TYPE"
        value: "v3applicationcredential"
      - name: "OS_APPLICATION_CREDENTIAL_ID"
        value: "b4ef7202e169497f8d15c3718c1a87ab"
      - name: "OS_APPLICATION_CREDENTIAL_SECRET"
        value: "WTkhB0xC00yKWQs6jnYl2inO9LJ-ZKwrKB1AEhQrxPbSETF6B9dY7Kf189OgtK14rGN7Erysc70znlQ-rWuw9w"
      - name: "OS_REGION_NAME"
        value: "kr-gov-central-1"
