apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2akNDQWRLZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1EY3dOREF6TXpBeU1sb1hEVE16TURjd01UQXpNelV5TWxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBT2lmCmlmWWRoL2NjazJsWkdnSitpYUZ5bExveVFDZ2o0N2RYblYzZytUWmZKcktjSzZ5a2htZFRocllJL2dRaWNrNWsKeGVYN1FqZk5sUDRsRVRMdnV2R3hQdGlPbVdsTUlQVzM1WVc3Qyt1aWNSWXNQbDc1STliOXk3UGgzSDJQT2p3VAo1Wkg2cGM5bTZxcmlvWW1abUI2QitOZ0dTbXp1dzdxdmRPUXpOeEdaUEdma1Y5YUN1SDJVeVlEbjNiWFNvdTFrCkpoNGJiV25zcncwcEx2cTM3UzBmRUlmN2dNM0xXUUhaSk11b3p1QytlVWpZOEpPNm5vdHlkTGFvU0dqYWxaMUkKODFNTjBobVNKL2h2cTNkc3UwZitmV2hKVmYzNURyS0hGRFdGNzRpaEJNRlMrTDNrM2lGRnBqejdnZmIyM2dtcgo1ZzY0RmpJTjI2RlJDaWgyb0VFQ0F3RUFBYU5GTUVNd0RnWURWUjBQQVFIL0JBUURBZ0trTUJJR0ExVWRFd0VCCi93UUlNQVlCQWY4Q0FRQXdIUVlEVlIwT0JCWUVGSkRZbE1XalE2OFZSd2JNZlYrRlIzbWxWbUhNTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQmhMbjRTQzZBQlRONCtYK0xWQTNTWlB0aHpGUUhFam9Yc0cxOW5ySjAzY3BCUQppYzNZWmUvZHY4cmlBQkZiNG9ZWWZ3UUpQN3RPZXBtRnRRc1FSMTFIK0ZiNEkydHA1c1Y5UjN5Y2xKYjdtUmN2CjA2RlV0TXJ2M0lHd0N4YW9YY0o3VHZ3WWplR3o1eHArQkJYQW9xTG9QNXllU09JMXUvanNaWHUwQW90S3dtMWYKdEpvaTZUUUUvQW1UZHZ3OUFDb1V6cmsyVDVUM0FlSGFIeStRZUtFT1U1MHhxc1FFTkh3cTBMYmQxUG1FSHkveQpjOFRtUVhFd3pJSG82UTE4Rmx4K2lDY1VuZHRrY0M2R2JGbXJzeWdqd0ljT2VvaGE5RDZZOEl5ekl1NmlBL1lMCjdhcjBCaFcySzB0RU1PV3hhRjdGeHVkeGVTcUhLbUJpNVorL1NpaTMKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://61.109.215.31:6443
  name: smtbrc-prod-mgmt
contexts:
- context:
    cluster: smtbrc-prod-mgmt
    user: smtbrc-prod-mgmt-admin
  name: smtbrc-prod-mgmt-admin@smtbrc-prod-mgmt
current-context: smtbrc-prod-mgmt-admin@smtbrc-prod-mgmt
kind: Config
preferences: {}
users:
- name: smtbrc-prod-mgmt-admin
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: kic-iam-auth
      env:
      - name: "OS_AUTH_URL"
        value: "https://iam.kakaoicloud-kr-gov.com/identity/v3"
      - name: "OS_AUTH_TYPE"
        value: "v3applicationcredential"
      - name: "OS_APPLICATION_CREDENTIAL_ID"
        value: "b4ef7202e169497f8d15c3718c1a87ab"
      - name: "OS_APPLICATION_CREDENTIAL_SECRET"
        value: "WTkhB0xC00yKWQs6jnYl2inO9LJ-ZKwrKB1AEhQrxPbSETF6B9dY7Kf189OgtK14rGN7Erysc70znlQ-rWuw9w"
      - name: "OS_REGION_NAME"
        value: "kr-gov-central-1"
