apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2akNDQWRLZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1EY3dNekF4TVRjd05Gb1hEVE16TURZek1EQXhNakl3TkZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS0VGCkNRU0thVXRUTmhJUVV1OUgwYzZQNmZOeUlTcTErSlFob3BOMDlqK1ZWdWYrL0RPcXoxQVd3b1JLVVhCb2FPTGIKa25DYXg1NjhNMDd1RHZ0MjVZUCs2OHp0c29nbmNIa3lXSlUyTUFBbklKUEpPQ3BwSzVhclFLNWZPNEJDODg2aQpsQmxxazBZMUF5ZG8xRDlNMklWMFNkRlQ2bmEwNHY4VTVmOGxmL3RoTlIzVFVKQmlJamt2L3d3eDRJMkgyL01uCmMyWmh1SC8wSkdnWk4rNEJ0UE04OXl1dlZ5TTFXRnZGdjhoRE96Ukp4ZnNqQTZ1V25vVnhIdEZVaFozd0tFN1UKSzFuUXprZ0wwRHdwQ25jeFlmZkRXZnRLMHl5ZW15eXU4UngwY3VWQ0pxMWV0UW5DM3RMR0Q2U3VJcEVJQXdZeAovb24rKy9OZTU3cnJkY1BiVkEwQ0F3RUFBYU5GTUVNd0RnWURWUjBQQVFIL0JBUURBZ0trTUJJR0ExVWRFd0VCCi93UUlNQVlCQWY4Q0FRQXdIUVlEVlIwT0JCWUVGTFJ5OXhrczJnVlBPbStHcFI1aE1pNXJla1cwTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQjl3YmhOdktBLzBHTkR0aGdTZUVydE9ya2dUQ3QvOElsK0xPQnpLYlB5VXpVdApPVVljVmxyZWhHY3ZjSlJPVStkcW1QZUNGZWN6SnJhK2pWVW1YMWU5TkhnMkFUR1E0dWpHN2NETHF4M1phdDIzCkJtbkJCUnc0bXlEOW5qL25WMHlqUnhpR3VPc0s0NEpFcm9STmU2Rk1pRlo2RTdaeXRmVmtZWWdnTzREVlRXeDgKZnNmaHBLQUxKNzhnMGhhYVIyd1pUalA3WUpETFFXbitNOHl6Mi9YWWtLc3o1SkxVUi9tV1YzT083ekRhekFxUApxcDQ3K1RaZnNVRjJQNXZLY2FBN3BOMEIrQ1podE8zVHdaK3k5OVRabjdOczEzZzEyNHR3Q1lxN09OUjR4aDV5ClI3VFpmcmlkYTRERFlTSVpjWngrWkNDck1KREtFSklXR0Q0Si8yZGYKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://61.109.215.102:6443
  name: smtbrc-prod-web
contexts:
- context:
    cluster: smtbrc-prod-web
    user: smtbrc-prod-web-admin
  name: smtbrc-prod-web-admin@smtbrc-prod-web
current-context: smtbrc-prod-web-admin@smtbrc-prod-web
kind: Config
preferences: {}
users:
- name: smtbrc-prod-web-admin
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: kic-iam-auth
      env:
      - name: "OS_AUTH_URL"
        value: "https://iam.kakaoicloud-kr-gov.com/identity/v3"
      - name: "OS_AUTH_TYPE"
        value: "v3applicationcredential"
      - name: "OS_APPLICATION_CREDENTIAL_ID"
        value: "b4ef7202e169497f8d15c3718c1a87ab"
      - name: "OS_APPLICATION_CREDENTIAL_SECRET"
        value: "WTkhB0xC00yKWQs6jnYl2inO9LJ-ZKwrKB1AEhQrxPbSETF6B9dY7Kf189OgtK14rGN7Erysc70znlQ-rWuw9w"
      - name: "OS_REGION_NAME"
        value: "kr-gov-central-1"
