apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  namespace: mgt
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: "grafana"
  claimRef:
    name: grafana-pvc
    namespace: mgt
  nfs:
    server: 172.30.16.205
    path: /smtbrc
